spring.application.name=backend

spring.datasource.url=jdbc:postgresql://dpg-cvo2p73uibrs738alu90-a.oregon-postgres.render.com:5432/raise_it_dev
spring.datasource.username=raise_it_dev_user
spring.datasource.password=N8vOYd2L8xJIO3Sm9Ep9D0Ayqlcvw5tL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
